services:
  nids-early-exit:
    build: ./traffic_agent
    container_name: nids_early_exit_agent
    restart: always
    network_mode: "host"
    cap_add:
      - NET_ADMIN 
    environment:
      - INTERFACE=wlp2s0
    logging:
      driver: "json-file"
      options:
        max-size: "10m"